# Generated by Django 5.0.4 on 2024-04-30 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.TextField(blank=True, null=True)),
                ('address_data', models.TextField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Address',
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='CardRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worldpay_order_code', models.CharField(max_length=50)),
                ('registration_status', models.CharField(max_length=20)),
                ('crm_card_token', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Card Registration',
                'db_table': 'card_registration',
            },
        ),
        migrations.CreateModel(
            name='CrmIdCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Crrm Id Code',
                'db_table': 'crm_id_code',
            },
        ),
        migrations.CreateModel(
            name='CrmIdDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Crm Id Description',
                'db_table': 'crm_id_description',
            },
        ),
        migrations.CreateModel(
            name='CustomerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_customer_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('contact_email', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Customer Registration',
                'db_table': 'customer_registration',
            },
        ),
        migrations.CreateModel(
            name='RegistrationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Registration Stages',
                'db_table': 'registration_stage',
            },
        ),
        migrations.CreateModel(
            name='StageDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Stage Description',
                'db_table': 'stage_description',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_auto_renew', models.BooleanField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('delivery_address_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineSalesapp.address')),
                ('installation_address_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_installation_address_set', to='onlineSalesapp.address')),
            ],
            options={
                'verbose_name_plural': 'Cart',
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_cart_item_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('cart_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineSalesapp.cart')),
            ],
            options={
                'verbose_name_plural': 'Cart Item',
                'db_table': 'cart_item',
            },
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('id_number', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=200)),
                ('is_promotion_consent', models.BooleanField()),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('billing_address_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineSalesapp.address')),
                ('card_registration_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineSalesapp.cardregistration')),
                ('customer_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineSalesapp.customerregistration')),
            ],
            options={
                'verbose_name_plural': 'Customer Account',
                'db_table': 'customer_account',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='customer_account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineSalesapp.customeraccount'),
        ),
        migrations.CreateModel(
            name='CustomerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_doc_filename', models.CharField(max_length=200)),
                ('uploaded_doc_filename', models.CharField(max_length=200)),
                ('is_uploaded', models.BooleanField()),
                ('crm_doc_path', models.CharField(max_length=200)),
                ('crm_doc_tool', models.CharField(max_length=10)),
                ('crm_doc_profile', models.CharField(max_length=20)),
                ('crm_doc_template', models.CharField(max_length=20)),
                ('crm_doc_type', models.CharField(max_length=10)),
                ('crm_doc_template_area', models.CharField(max_length=20)),
                ('uploaded_doc_type', models.CharField(max_length=20)),
                ('modified_date', models.DateTimeField()),
                ('created_date', models.DateTimeField()),
                ('cart_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineSalesapp.cart')),
                ('customer_account_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineSalesapp.customeraccount')),
            ],
            options={
                'verbose_name_plural': 'Customer Document',
                'db_table': 'customer_document',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='customer_registration_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineSalesapp.customerregistration'),
        ),
        migrations.CreateModel(
            name='IdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_id_code_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineSalesapp.crmidcode')),
                ('crm_id_description_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineSalesapp.crmiddescription')),
            ],
            options={
                'verbose_name_plural': 'Id Types',
                'db_table': 'id_type',
            },
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='id_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineSalesapp.idtype'),
        ),
        migrations.CreateModel(
            name='PortingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.CharField(max_length=15)),
                ('operator_code', models.CharField(max_length=15)),
                ('operator_name', models.CharField(max_length=100)),
                ('is_prepaid', models.BooleanField()),
                ('iccid', models.CharField(blank=True, max_length=20, null=True)),
                ('is_owner', models.BooleanField()),
                ('owner_first_name', models.CharField(max_length=100)),
                ('owner_last_name', models.CharField(max_length=100)),
                ('owner_id_number', models.CharField(max_length=15)),
                ('owner_nationality', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('cart_item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineSalesapp.cartitem')),
                ('owner_id_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineSalesapp.idtype')),
            ],
            options={
                'verbose_name_plural': 'Porting Data',
                'db_table': 'porting_data',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_product_code', models.CharField(max_length=10)),
                ('crm_description', models.CharField(max_length=100)),
                ('crm_service_yn', models.CharField(max_length=100)),
                ('crm_package_yn', models.CharField(max_length=100)),
                ('crm_service_cd', models.CharField(max_length=100)),
                ('crm_number_plan_code', models.CharField(blank=True, max_length=10, null=True)),
                ('display_information', models.CharField(blank=True, max_length=200, null=True)),
                ('crm_comp_group_code', models.CharField(blank=True, max_length=10, null=True)),
                ('crm_parent_package_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('cart_item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineSalesapp.cartitem')),
            ],
            options={
                'verbose_name_plural': 'Product',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_product_code', models.CharField(max_length=10)),
                ('price_type', models.CharField(max_length=10)),
                ('price_version', models.IntegerField()),
                ('tax_category', models.CharField(max_length=10)),
                ('tax_rate', models.FloatField()),
                ('tax_included_amount', models.FloatField()),
                ('tax_excluded_amount', models.FloatField()),
                ('price_start_date', models.DateField()),
                ('price_end_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('cart_item_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineSalesapp.cartitem')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineSalesapp.product')),
            ],
            options={
                'verbose_name_plural': 'product_price',
                'db_table': 'product_price',
            },
        ),
        migrations.AddField(
            model_name='customerregistration',
            name='registration_stage_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineSalesapp.registrationstage'),
        ),
        migrations.AddField(
            model_name='registrationstage',
            name='stage_description_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineSalesapp.stagedescription'),
        ),
    ]
