# Generated by Django 5.0.4 on 2024-05-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineSalesapp', '0002_alter_address_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
